highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyllt.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# jekyllt.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title:
name:  Alejandro Hernández-Arango
email: alejandro.hernandeza@udea.edu.do
email_full: mailto:alejandro.hernandeza@udea.edu.do
website: github.io/alejo760
website_full: https://alejo760.github.io/
github: alejo760
twitter: @arangoalejo
tel: 
tel_full: tel:+6042196000
google_maps: 'https://www.google.com/maps/place/Facultad+de+Medicina,+Universidad+de+Antioquia/@6.2612493,-75.5685166,17z/data=!3m1!4b1!4m5!3m4!1s0x8e4428e4f7f83e59:0xb4478f7b5de646fb!8m2!3d6.2612493!4d-75.5663225?hl=esL'
address:
  street: Carrera 51D # 64
  postcode: 
  city: Medelllin
  country: Colombia
google_analytics: G-WZV5VX496G

# needed for travis-ci build
exclude: [vendor]
